### ISSUE TITLE
High-order modeling

### ISSUE THREAD

**Issue by alexisrozhkov** [yu-lab-vt/muSSP#11]
I would like to try reproducing results, mentioned in the section 4.2 of the paper (`Solving the min-cost flow approximation to the high-order modeling in MOT`), but I am a bit vague on the exact steps, that need to be taken in order to do this.

From what I understood, 2 things are needed:
* Construction of graph with quadratic costs
* Optimization loop, which uses min-cost flow solver as a sub-routine

Can you please point to an appropriate publication with more details on this or an implementation, ideally the one that was used during preparation of the paper?

**Comment by ccwang92** [comment]
Hi Alexey,
Sure. You can find the way to construct the quadratic graph (the quadratic programming formulation) in this paper (https://arxiv.org/pdf/1408.3304.pdf). Their code is also available here (https://github.com/viseshchari/TrackingNetFlow). To solve the quadratic programming problem with min-cost flow, we used Frank-Wolfe algorithm (https://en.wikipedia.org/wiki/Frank%E2%80%93Wolfe_algorithm). It is an iterative methods and reduced the quadratic problem as a min-cost flow problem in each iteration. muSSP was used to solve the min-cost flow problem in each iteration.

Best,

**Comment by alexisrozhkov** [comment]
Thank you, I really appreciate your help, and great work with muSSP!
