### ISSUE TITLE
Memory Leak in Graph::extract_shortest_path()

### ISSUE THREAD

**Issue by FloatFlow** [yu-lab-vt/muSSP#12]
Given certain graphs and edge weight magnitudes, `Graph::extract_shortest_path()` will fetch an invalid int for `tmp_node_id`, resulting in a segmentation fault. Example file is attached.
[mussp_segfault_dimacs.txt.zip](https://github.com/yu-lab-vt/muSSP/files/8392779/mussp_segfault_dimacs.txt.zip)

**Comment by yu-lab-vt** [comment]
Dear @FloatFlow,

Thank you for pointing this out. We are looking into the problem and will get back to you soon.

Yu Lab at Virginia Tech

**Comment by ccwang92** [comment]
Hi FloatFlow,

The error was caused  by function Graph::invalid_edge_rm(), which assumes that the pre-node and post-node for the same detection have continous node id (e.g. node 2 and 3 are used to represent the same node). In your graph, this is not true. You can either comment out this function (line 111 in main.cpp) or manipulate your graph based on the assumption. I have verified that the former way works.

Thanks,

**Comment by FloatFlow** [comment]
Thank you for the quick follow up
