### ISSUE TITLE
Running in real-time

### ISSUE THREAD

**Issue by rcarbonn** [yu-lab-vt/muSSP#15]
I want to run this algorithm in an online manner i.e. I have new detections coming in and I want to grow the graph and optimize it at each time step. Is it possible with the current implementation?

**Comment by yu-lab-vt** [comment]
Unfortunately, muSSP was designed for off-line computation. New design is
needed for the online manner.

Guoqiang Yu

**Comment by rcarbonn** [comment]
Understood. Thanks!
