### ISSUE TITLE
Trajectories share detections

### ISSUE THREAD

**Issue by lcit** [yu-lab-vt/muSSP#3]
Hello, thanks you for sharing this code!
I have tried it and noticed that different trajectories may have some detections in common. Is this a wanted feature or am I doing something wrong?

**Comment by yu-lab-vt** [comment]
Hi lcit, this is not a wanted feature. I did not see this problem in my experiments. Would you mind send me a sample input? It would be interesting to double-check the reason behind it. My email is ccwang@vt.edu.
Thank you!

**Comment by lcit** [comment]
The error was on my side. The algorithm does not produce trajectories that have detection in common.
