### ISSUE TITLE
About Licensing

### ISSUE THREAD

**Issue by yukkysaito** [yu-lab-vt/muSSP#7]
@yu-lab-vt 
Thank you for publishing so wonderful.
I'm a developper of OSS for automaus driving.
https://github.com/tier4/Pilot.Auto
I evaluated the muSSP and found that it was faster than ours and performed very well since the matrix size was 100x100.
I would really like to use this muSSP, but there is no description of the license.
Can you please add a license, Apache 2.0 would be great!

**Comment by yu-lab-vt** [comment]
Hi @yukkysaito,

Sure. The license has been added. And thank you for your interest in muSSP! Feedbacks and suggestions are strongly welcome.

Best,

**Comment by yukkysaito** [comment]
Very fast work!
Thank you very much.

**Comment by yukkysaito** [comment]
@yu-lab-vt Sorry for replying so many times.
can you please write copyright?
https://github.com/yu-lab-vt/muSSP/blob/master/LICENSE#L189

**Comment by yu-lab-vt** [comment]
Updated. Thanks for pointing this out.

**Comment by yukkysaito** [comment]
thank you so much
