### ISSUE TITLE
input_MOT_seq07_followme.txt 

### ISSUE THREAD

**Issue by JACKLU-12** [yu-lab-vt/muSSP#9]
Hello, I am very interested in your work. I would like to ask you about the input data, how the file input_MOT_seq07_followme.txt is generated

**Comment by yu-lab-vt** [comment]
Hi JACKLU-12, we did not fully understand your question. Are you asking about the format of the file? If so, the "input_MOT_seq07_followme.txt" saves the graph in the DIMACS format with a slight edit. Below we give a brief introduction of DIMACS format edited from http://lcs.ios.ac.cn/~caisw/Resource/about_DIMACS_graph_format.txt:

1. Problem line. There is one problem line per input file. The problem line must appear before any node or arc descriptor lines. The problem line has the following format. E.g. "p PROBLEM_DEFINE #NODES #EDGES"

2. Comments. Comment lines give human-readable information about the file and are ignored by programs. Comment lines can appear anywhere in the file. Each comment line begins with a lower-case character c.  E.g. "c This is an example of a comment line."

3. Arc Descriptors. There is one arc descriptor line for each directed arc (u,v) of the graph, starting with "a" in the following format: "a u v cost". Each arc (u,v) appears exactly once in the input file. "cost" is the arc cost. All arc capacity is exactly one, so capacity info is omitted here.

If you are asking about how to design the graph and infer the cost of arcs from the detection results. I refer you to the second section of our paper (https://drive.google.com/file/d/1BUkWpkX-QagNY5vxP0H_QuyIIFbfMtfK/view) for details. There is also a description of it in the classic work here (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.318.9857&rep=rep1&type=pdf).

Best,

**Comment by yu-lab-vt** [comment]
@JACKLU-12 , Hi, JackLu, please let us know whether we addressed your questions.

**Comment by JACKLU-12** [comment]
yes！Thank you very much! Wish you have a good day.


















At 2021-02-01 11:39:51, "Yu Lab at Virginia Tech" <notifications@github.com> wrote:

@JACKLU-12 , Hi, JackLu, please let us know whether we addressed your questions.
